AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Shortify SAM
  Sample SAM Template for Shotfify SAM
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'GET'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      
Resources:
  ShortifyFunction:
    Type: AWS::Serverless::Function 
    Properties: 
      CodeUri: src/main/java/com/amazonaws/shortify/
      Handler: Shortify.lambdaHandler
      Runtime: java8.x
      Policies: AmazonDynamoDBFullAccess
      Events: 
        UserDetails:
          Type: Api
          Properties:
            Path: /shortify/createURL
            Method: post

  LongURLFunction:
    Type: AWS::Serverless::Function 
    Properties: 
      CodeUri: src/main/java/com/amazonaws/shortify/
      Handler: GetLongUrl.lambdaHandler
      Runtime: java8.x
      Policies: AmazonDynamoDBFullAccess
      Events: 
        UserDetails:
          Type: Api
          Properties:
            Path: /{shortUrl}
            Method: get

  Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ShortifyAPI:
    Description: "API Gateway endpoint URL for Prod stage shortify function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/shortify/"

  LongURLApi:
    Description: "API Gateway endpoint URL for Prod stage for long URL function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/{shorturl}/"
